### ISSUE TITLE
Sanitisation bypasses

### ISSUE THREAD

**Issue by the-cartographer** [braintree/inject-stylesheet#19]
Hi,

Back in June I reported two bugs in the inject-stylesheet library via the PayPal bug bounty program. In places where inject-stylesheet is being used for CSS sanitisation, it is possible to have non-permitted CSS properties accepted/applied and use restricted CSS functions such as `url()` 

The report was closed as Informational and is not currently public, but for reference it is https://hackerone.com/reports/1244272 

I tried reaching out to `ppbugbounty@paypal.com` to confirm if a bug report had been passed onto the development team but didn't get a response. I just wanted to confirm if the development team were aware of these issues and if there was an ETA on when a fix might be available?

Please let me know if there is anything additional I can provide that will help.

Thanks!

**Comment by crookedneighbor** [comment]
This was never passed on to us, as far as I know. I also don't have access to the report. 

Can you provide an example of a vulnerable configuration here?

**Comment by the-cartographer** [comment]
Hi @crookedneighbor

Thanks for the quick response

```
input: {
  'color':'red&background-image:\\75\\72\\6C(https://media.giphy.com/media/Ju7l5y9osyymQ/giphy.gif)'
}
```

The first bug takes advantage of the [htmlEscape](https://github.com/braintree/inject-stylesheet/blob/c3faf4b4adfce4a02d2c06a77be3e564d76f5616/src/lib/filter-style-values.ts#L18) function. By appending an unnecessary `&` to the end of the previous property value, the required delimiter `;` gets introduced into the string. This enables an unsupported property to be appended when `red&background-image` gets encoded as `red&amp;background-image`.

The second bug uses CSS escapes to avoid sanitisation of any filtered strings, such as `\75\72\6C` instead of `url` in this example.

**Comment by crookedneighbor** [comment]
Thanks so much for the example! You're definitely right, this needs immediate attention.

**Comment by crookedneighbor** [comment]
I've also asked our security engineers to review the hackerone report you submitted

**Comment by the-cartographer** [comment]
Thanks for picking this up and fixing it so quickly @crookedneighbor and @hollabaq86 (no doubt it meant dropping other things), really appreciate it 😃

**Comment by crookedneighbor** [comment]
:+1:

We're not quite finished with the work, but I hope for it to be complete by tomorrow.

**Comment by crookedneighbor** [comment]
OK, it should be all deployed with the fix. Thanks again so much for reporting this here. If within a few weeks the PayPal security team hasn't reached out to you about this, please comment here and I'll poke it along from my end.

**Comment by the-cartographer** [comment]
Thanks, will do!

**Comment by the-cartographer** [comment]
Hey @crookedneighbor hope you're well.

I haven't heard anything from the security team yet - any chance you could ping them from your side?

I'll add a link to this Github issue on the Hackerone report for the triage team to pass along, hopefully it'll give some additional context and help find the right person in the security team.

**Comment by crookedneighbor** [comment]
Thanks for checking in, I'll ping some folks.

**Comment by crookedneighbor** [comment]
It's still in process, but is nearing completion. If you haven't heard anything by the end of next week, ping me again. It's important to me that you get recognized for this!

**Comment by the-cartographer** [comment]
Thanks again, really appreciate it. There's been some activity on the hackerone report just now which seems promising, will wait and see what happens from here 😃

**Comment by crookedneighbor** [comment]
@the-cartographer just checking back in on this. Did the hackerone report ever get closed out?

**Comment by the-cartographer** [comment]
Hey @crookedneighbor, sorry for the slow response. Yes it did! 🎉  I've requested disclosure of the report (not sure if/when that might happen), but it was eventually reopened, triaged and upgraded from an informational finding to a medium severity issue thanks to you.

Patching the bugs so quickly was impressive but following up with people on your side about the report was above and beyond. Thanks again for all your help, I really appreciate it 😃
